### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by i-am-offline** [i-am-offline/smarthome.plugin.autoblind#12]
Documentation needs to be updated before releasing the next version.

Issues which require changes in documentation:
- [x] #5 Problems with suspend timer --> Explain new suspend mechanism
- [x] #6 repeat_actions specific for single actions? --> Explain new functionality
- [x] #10 Enable ordering of actions --> Explain new functionality (once realized)
- [x] #11 Allow different actions for entering, staying at and leaving a state --> Explain new functionality

Other changes
- [x] think about splitting documentation into several pages

**Comment by onkelandy** [comment]
https://github.com/i-am-offline/smarthome.plugin.autoblind/wiki/Doku-De-Vollstaendiges-Beispiel

as_minage und as_maxage sind hier falsch eingetragen

**Comment by i-am-offline** [comment]
Korrigiert

**Comment by i-am-offline** [comment]
Documentation for 1.2.2 is sufficient. However, additional rework is needed for future versions.
